--
-- CREATE TABLE book(
--     book_id INT PRIMARY KEY AUTO_INCREMENT,
--     title VARCHAR(50),
--     author VARCHAR(30),
--     price DECIMAL(8, 2),
--     amount INT
-- );
--
-- INSERT INTO book (title, author, price, amount)
-- VALUES ('Мастер и Маргарита', 'Булгаков М.А.', 670.99, 3);
-- SELECT *
-- FROM book
--
-- INSERT INTO book (title, author, price, amount)
-- VALUES (
--         'Белая гвардия',
--         'Булгаков М.А.',
--         540.50,
--         5
--     ),
--     (
--         'Идиот',
--         'Достоевский Ф.М.',
--         460.00,
--         10
--     ),
--     (
--         'Братья Карамазовы',
--         'Достоевский Ф.М.',
--         799.01,
--         2
--     );
-- SELECT *
-- FROM book;
--
-- SELECT *
-- FROM book;
--
-- SELECT author,
--     title,
--     price
-- FROM book;
--
-- SELECT title AS Название,
--     amount
-- FROM book;
-- SELECT title AS Название,
--     author AS Автор
-- FROM book;
--
-- SELECT title,
--     author,
--     price,
--     amount,
--     price * amount AS total
-- FROM book;
--
-- SELECT title,
--     amount,
--     1.65 * amount AS pack
-- FROM book;
--
-- SELECT title,
--     price,
--     (price * 18 / 100) /(1 + 18 / 100) AS tax,
--     price /(1 + 18 / 100) AS price_tax
-- FROM book;
--
-- SELECT title,
--     price,
--     ROUND((price * 18 / 100) /(1 + 18 / 100), 2) AS tax,
--     ROUND(price /(1 + 18 / 100), 2) AS price_tax
-- FROM book;
--
-- SELECT title,
--     author,
--     amount,
--     ROUND(price * 0.7, 2) AS new_price
-- FROM book;
--
-- SELECT title,
--     amount,
--     price,
--     IF(amount < 4, price * 0.5, price * 0.7) AS sale
-- FROM book;
--
-- SELECT title,
--     amount,
--     price,
--     ROUND(IF(amount < 4, price * 0.5, price * 0.7), 2) AS sale
-- FROM book;
--
-- SELECT
--     title,
--     amount,
--     price,
--     ROUND(
--         IF(
--             amount < 4,
--             price * 0.5,
--             IF(amount < 11, price * 0.7, price * 0.9)
--         ),
--         2
--     ) AS sale,
--     IF(
--         amount < 4,
--         'скидка 50%',
--         IF(amount < 11, 'скидка 30%', 'скидка 10%')
--     ) AS Ваша_скидка
-- FROM
--     book;
-- SELECT
--     author,
--     title,
--     ROUND(
--         IF (
--             author = 'Булгаков М.А.',
--             price * 1.1,
--             IF (author = 'Есенин С.А.', price * 1.05, price)
--         ),
--         2
--     ) AS new_price,
-- FROM
--     book;
-- 
--
-- SELECT title,
--     price
-- FROM book
-- WHERE price < 600;
--
-- SELECT title,
--     author,
--     price * amount AS total
-- FROM book
-- WHERE price * amount > 4000;
--
-- SELECT
--     author,
--     title,
--     price
-- FROM
--     book
-- WHERE
--     amount < 10;
-- 
-- SELECT
--     title,
--     author,
--     price
-- FROM
--     book
-- WHERE
--     price > 600
--     AND author = 'Булгаков М.А.';
--
-- SELECT
--     title,
--     author,
--     price,
--     amount
-- FROM
--     book
-- WHERE
--     (
--         price < 500
--         OR price > 600
--     )
--     AND price * amount >= 5000;
--
-- SELECT
--     title,
--     author
-- FROM
--     book
-- WHERE
--     price BETWEEN 540.5
--     AND 800
--     AND amount IN (2, 3, 5, 7);
--
-- SELECT
--     author,
--     title
-- FROM
--     book
-- WHERE
--     amount BETWEEN 2
--     AND 14
-- ORDER BY
--     author DESC,
--     title ASC;
--
SELECT
    title,
    author
FROM
    book
WHERE
    title LIKE "%_ _%"
    AND author LIKE "%С.%"
ORDER BY
    title;